import React from 'react'

/**
 * Renders one slide as HTML from the same JSON generatePpt uses, so the
 * preview matches the real .pptx. Sized on a 16:9 box via absolute percentages
 * so the identical markup works as a thumbnail and as the main view.
 */
function SlidePreview({ slide, index, total, cover, title, subtitle }) {
  const layout = String(slide?.layout ?? '').toLowerCase().trim()
  const points = Array.isArray(slide?.points) ? slide.points.filter(Boolean) : []

  const Frame = ({ dark = false, children }) => (
    <div className={`relative w-full h-full overflow-hidden ${dark ? 'bg-[#0F172A]' : 'bg-white'}`}>
      <div className={`absolute inset-x-0 top-0 h-[1.9%] ${dark ? 'bg-[#60A5FA]' : 'bg-[#2563EB]'}`} />
      {children}
      {!cover && (
        <>
          <span className={`absolute left-[5%] bottom-[4%] text-[2.6cqw] ${dark ? 'text-[#94A3B8]' : 'text-[#64748B]'}`}>
            AmeekAI
          </span>
          <span className={`absolute right-[5%] bottom-[4%] text-[2.6cqw] ${dark ? 'text-[#94A3B8]' : 'text-[#64748B]'}`}>
            {index} / {total}
          </span>
        </>
      )}
    </div>
  )

  if (cover) {
    return (
      <Frame dark>
        <div className='absolute left-[5%] right-[10%] top-[34%]'>
          <div className='w-[12%] h-[0.8%] bg-[#60A5FA] mb-[3%]' />
          <p className='text-[6.4cqw] font-bold leading-tight text-white'>{title}</p>
          {subtitle && <p className='mt-[3%] text-[3cqw] text-[#DBEAFE]'>{subtitle}</p>}
        </div>
        <span className='absolute left-[5%] bottom-[4%] text-[2.6cqw] text-[#94A3B8]'>Generated by AmeekAI</span>
      </Frame>
    )
  }

  if (layout === 'section') {
    return (
      <Frame dark>
        <div className='absolute left-[5%] right-[8%] top-[32%]'>
          <p className='text-[6.6cqw] font-bold text-[#60A5FA]'>{String(index).padStart(2, '0')}</p>
          <p className='mt-[1%] text-[5cqw] font-bold leading-tight text-white'>{slide?.title}</p>
          {points[0] && <p className='mt-[3%] text-[2.9cqw] text-[#DBEAFE]'>{points[0]}</p>}
        </div>
      </Frame>
    )
  }

  const Title = () => (
    <>
      <p className='absolute left-[5%] right-[5%] top-[7%] text-[4.2cqw] font-bold text-[#0F172A] leading-tight'>
        {slide?.title}
      </p>
      <div className='absolute left-[5%] top-[17%] w-[12%] h-[0.7%] bg-[#2563EB]' />
    </>
  )

  const body = 'absolute left-[5%] right-[5%] top-[22%] bottom-[12%]'

  if (layout === 'cards' && points.length) {
    return (
      <Frame>
        <Title />
        <div className={`${body} flex gap-[2%]`}>
          {points.slice(0, 3).map((p, i) => (
            <div key={i} className='flex-1 bg-[#F8FAFC] border border-[#E2E8F0] rounded-[0.6cqw] overflow-hidden'>
              <div className='h-[3%] bg-[#2563EB]' />
              <p className='px-[8%] pt-[8%] text-[5cqw] font-bold text-[#60A5FA]'>{String(i + 1).padStart(2, '0')}</p>
              <p className='px-[8%] pt-[4%] text-[2.7cqw] text-[#334155] leading-snug'>{p}</p>
            </div>
          ))}
        </div>
      </Frame>
    )
  }

  if ((layout === 'statistics' || layout === 'stats') && points.length) {
    const split = (p) => {
      const m = String(p).match(/^\s*([€$£]?[\d][\d.,]*\s*(?:%|x|X|\+|k|K|M|bn)?)\s*[-–—:]?\s*(.*)$/)
      return m && m[1] ? [m[1].trim(), m[2].trim()] : [null, String(p)]
    }
    return (
      <Frame>
        <Title />
        <div className={`${body} flex gap-[2%]`}>
          {points.slice(0, 3).map((p, i) => {
            const [fig, label] = split(p)
            return (
              <div key={i} className='flex-1 flex flex-col items-center justify-center bg-[#EFF6FF] border border-[#E2E8F0] rounded-[0.6cqw] px-[4%]'>
                <p className='text-[7.5cqw] font-bold text-[#2563EB] leading-none'>{fig ?? '—'}</p>
                <p className='mt-[8%] text-[2.5cqw] text-[#334155] text-center leading-snug'>{label}</p>
              </div>
            )
          })}
        </div>
      </Frame>
    )
  }

  if (['two-column', 'comparison', 'table'].includes(layout) && points.length > 1) {
    const half = Math.ceil(points.length / 2)
    return (
      <Frame>
        <Title />
        <div className={`${body} flex gap-[2.5%]`}>
          {[points.slice(0, half), points.slice(half)].map((col, c) => (
            <div key={c} className={`flex-1 rounded-[0.6cqw] border border-[#E2E8F0] p-[3%] ${c === 0 ? 'bg-[#EFF6FF]' : 'bg-[#F8FAFC]'}`}>
              {col.slice(0, 5).map((p, i) => (
                <div key={i} className='flex gap-[3%] mb-[4%]'>
                  <span className='mt-[1.4%] w-[1.6cqw] h-[1.6cqw] rounded-full bg-[#2563EB] shrink-0' />
                  <p className='text-[2.5cqw] text-[#334155] leading-snug'>{p}</p>
                </div>
              ))}
            </div>
          ))}
        </div>
      </Frame>
    )
  }

  if (['process', 'timeline', 'diagram'].includes(layout) && points.length > 1) {
    const steps = points.slice(0, 5)
    return (
      <Frame>
        <Title />
        <div className={`${body}`}>
          <div className='relative flex items-start justify-between pt-[3%]'>
            <div className='absolute left-[10%] right-[10%] top-[4.6cqw] h-[1px] bg-[#E2E8F0]' />
            {steps.map((p, i) => (
              <div key={i} className='relative flex-1 flex flex-col items-center px-[1%]'>
                <span className='flex items-center justify-center w-[5cqw] h-[5cqw] rounded-full bg-[#2563EB] text-white text-[2.4cqw] font-bold'>
                  {i + 1}
                </span>
                <p className='mt-[10%] text-[2.3cqw] text-[#334155] text-center leading-snug'>{p}</p>
              </div>
            ))}
          </div>
        </div>
      </Frame>
    )
  }

  if (layout === 'quote' && points.length) {
    return (
      <Frame>
        <Title />
        <div className={body}>
          <p className='text-[9cqw] font-bold text-[#60A5FA] leading-none'>&ldquo;</p>
          <p className='mt-[-2%] pl-[6%] pr-[8%] text-[3.6cqw] italic text-[#0F172A] leading-snug'>{points[0]}</p>
          {points[1] && <p className='mt-[5%] pl-[6%] text-[2.4cqw] text-[#64748B]'>{points[1]}</p>}
        </div>
      </Frame>
    )
  }

  if (['key-takeaway', 'closing'].includes(layout) && points.length) {
    return (
      <Frame>
        <Title />
        <div className={`${body} rounded-[0.6cqw] bg-[#2563EB] p-[4%]`}>
          {points.slice(0, 4).map((p, i) => (
            <p key={i} className={`text-[3cqw] text-white mb-[3%] ${i === 0 ? 'font-bold' : ''}`}>{p}</p>
          ))}
        </div>
      </Frame>
    )
  }

  return (
    <Frame>
      <Title />
      <div className={body}>
        {points.slice(0, 6).map((p, i) => (
          <div
            key={i}
            className={`flex items-center gap-[2%] mb-[1.6%] px-[2.5%] py-[1.8%] rounded-[0.5cqw] border border-[#E2E8F0]
              ${i % 2 ? 'bg-[#F8FAFC]' : 'bg-[#EFF6FF]'}`}
          >
            <span className='w-[1.6cqw] h-[1.6cqw] rounded-full bg-[#2563EB] shrink-0' />
            <p className='text-[2.6cqw] text-[#334155] leading-snug'>{p}</p>
          </div>
        ))}
      </div>
    </Frame>
  )
}

export default SlidePreview
